module FileIO where

import System.IO
import System.Directory
import Data.List (intercalate)
import Types

saveList :: FilePath -> ShoppingList -> IO ()
saveList filePath list = do
  let content = unlines $ map itemToCSV list
  writeFile filePath content
  putStrLn $ "List saved to " ++ filePath ++ " (" ++ show (length list) ++ " items)"

loadList :: FilePath -> IO (Either String ShoppingList)
loadList filePath = do
  exists <- doesFileExist filePath
  if not exists
    then return $ Left "File does not exist"
    else do
      content <- readFile filePath
      return $ mapM csvToItem (lines content)

itemToCSV :: ShoppingItem -> String
itemToCSV item = intercalate "," $
  [ show (itemId item)
  , itemName item
  , show (quantity item)
  , show (price item)
  , show (category item)
  , show (priority item)
  , show (purchased item)
  ]

csvToItem :: String -> Either String ShoppingItem
csvToItem line = 
  case splitOn ',' line of
    [idStr, name, qtyStr, priceStr, catStr, priStr, purStr] ->
      case (reads idStr, parseInt qtyStr, reads priceStr, 
            parseCategory catStr, parsePriority priStr, reads purStr) of
        ([(id, "")], Right qty, [(pr, "")], Right cat, Right pri, [(pur, "")]) ->
          Right $ ShoppingItem id name qty pr cat pri pur
        _ -> Left "Invalid CSV format"
    _ -> Left "Invalid CSV format"

splitOn :: Char -> String -> [String]
splitOn delim = foldr splitter [[]]
  where
    splitter c (x:xs)
      | c == delim = [] : x : xs
      | otherwise = (c:x) : xs
    splitter _ [] = []

exportFormatted :: FilePath -> ShoppingList -> IO ()
exportFormatted filePath list = do
  let header = "SHOPPING LIST REPORT\n" ++
               "===================\n\n" ++
               "Total Items: " ++ show (length list) ++ "\n" ++
               "Total Cost: $" ++ show (totalCost list) ++ "\n\n" ++
               "ITEMS:\n" ++
               "------\n"
      itemsText = unlines $ map (\item -> 
        "• " ++ itemName item ++ 
        " x" ++ show (quantity item) ++ 
        " @ $" ++ show (price item) ++ 
        " = $" ++ show (price item * fromIntegral (quantity item)) ++
        " [" ++ show (category item) ++ ", " ++ show (priority item) ++ "]" ++
        if purchased item then " ✓" else ""
        ) list
      footer = "\nGenerated by Haskell Shopping List Manager"
  writeFile filePath (header ++ itemsText ++ footer)
  putStrLn "Formatted report exported successfully"